### ISSUE TITLE
What is the license of the project?

### ISSUE THREAD

**Issue by thedemons** [Fleynaro/SDA#6]
Hi, first of all, thanks for creating an amazing project!

I couldn't help but notice that you're making a new decompiler from scratch, that is so challenging to do.

I'm trying to make something like this myself, it also uses ImGui, and looking for open-source decompilers that I can integrate into it. So I wanted to know what is the license for your decompiler?

Thanks!

**Comment by Fleynaro** [comment]
Hi! The license is Apache License 2.0
